name: github pages
permissions:
  contents: write
on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v2.5.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd docs && npm install && hugo --minify

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@ec9c88baef04b842ca6f0a132fd61c762aa6c1b0 # v4.6.0
        with:
          folder: ./docs/public # The folder the action should deploy.
