name: github pages
permissions:
  contents: write
on:
  push:
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.5.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd docs && npm install && hugo --minify

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@65b5dfd4f5bcd3a7403bbc2959c144256167464e # v4.5.0
        with:
          folder: ./docs/public # The folder the action should deploy.
