name: github pages
permissions:
  contents: write
on:
  push:
    paths:
      - "docs/**"
    branches:
      - main  # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # v2.5.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: cd docs && npm install && hugo --minify

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@ba1486788b0490a235422264426c45848eac35c6 # v4.4.0
        with:
          folder: ./docs/public # The folder the action should deploy.
