name: Validate SPDX Conformance

on:
  pull_request:
    branches: ['main']

jobs:
  check-spdx:
    name: Check SPDX SBOMs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v3.3.0
        with:
          go-version: '1.22'
          check-latest: true

      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - run: |
          go run ./cmd/bom/main.go generate -i registry.k8s.io/pause > example-image-pause.spdx
          go run ./cmd/bom/main.go generate --format=json -i registry.k8s.io/pause > example-image-pause.spdx.json

      - uses: chainguard-dev/actions/setup-spdx@d886686603afb809f7ef9b734b333e20b7ce5cda
        with:
          spdx-tools-version: 1.1.0

      - uses: chainguard-dev/actions/setup-spdx@d886686603afb809f7ef9b734b333e20b7ce5cda
        with:
          download: false
          spdx-tools-version: 1.1.0
          sbom-path: example-image-pause.spdx

      - uses: chainguard-dev/actions/setup-spdx@d886686603afb809f7ef9b734b333e20b7ce5cda
        with:
          download: false
          spdx-tools-version: 1.1.0
          sbom-path: example-image-pause.spdx.json

      - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808  # v4.3.3
        if: ${{ always() }}
        with:
          name: Example SBOMs
          path: |
            example-image-pause.spdx
            example-image-pause.spdx.json
